apiVersion: v1
kind: Pod
metadata:
  name: demo-app
spec:
  containers:
  - name: demo-app
    image: hashicorp/http-echo:latest
    envFrom:
    - configMapRef:
        name: demo-app-config
    env:
    - name: JWT_ISSUER_SECOND
      valueFrom:
        configMapKeyRef:
          name: demo-app-config
          key: JWT_ISSUER
